[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
chainy = "34CUrzPkzNS4hV3u8CXMsM73pXnv3FFPHCk1WkVBcRwY"
tile = "DfMmQL1ozAyHTkNMEDBXWi7CV8AutqXUcrGJR4BvwmUS"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/gabrielepicco/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"


[[test.genesis]]
address = "WorLD15A7CrDwLcLy4fRqtaTb9fbd8o8iqiEMUDse2n"
program = "tests/fixtures/world.so"
